SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS action_key                       ;
DROP TABLE IF EXISTS action_key_value                 ;
DROP TABLE IF EXISTS action_value                     ;
DROP TABLE IF EXISTS actions                          ;
DROP TABLE IF EXISTS attribute_values                 ;
DROP TABLE IF EXISTS attributes                       ;
DROP TABLE IF EXISTS audit_log                        ;
DROP TABLE IF EXISTS charts                           ;
DROP TABLE IF EXISTS criteria                         ;
DROP TABLE IF EXISTS design                           ;
DROP TABLE IF EXISTS employee_attribute_values        ;
DROP TABLE IF EXISTS employee_report_method           ;
DROP TABLE IF EXISTS employee_role                    ;
DROP TABLE IF EXISTS employee_status                  ;
DROP TABLE IF EXISTS employee_tokens                  ;
DROP TABLE IF EXISTS employees                        ;
DROP TABLE IF EXISTS folders                          ;
DROP TABLE IF EXISTS group_attributes                 ;
DROP TABLE IF EXISTS groups                           ;
DROP TABLE IF EXISTS includes                         ;
DROP TABLE IF EXISTS methods                          ;
DROP TABLE IF EXISTS report_analytic_criteria         ;
DROP TABLE IF EXISTS report_analytic_design           ;
DROP TABLE IF EXISTS report_analytic_includes         ;
DROP TABLE IF EXISTS report_analytics                 ;
DROP TABLE IF EXISTS report_folder                    ;
DROP TABLE IF EXISTS role_type_action_permission      ;
DROP TABLE IF EXISTS role_type_group_attribute_action ;
DROP TABLE IF EXISTS roles                            ;
DROP TABLE IF EXISTS status                           ;
DROP TABLE IF EXISTS type_action_permission           ;
DROP TABLE IF EXISTS type_group_attribute_permission  ;
DROP TABLE IF EXISTS types                            ;

DROP TABLE IF EXISTS assigned             ;
DROP TABLE IF EXISTS attachments          ;
DROP TABLE IF EXISTS employee_attachments ;

DROP VIEW IF EXISTS v_employee_attribute             ;
DROP VIEW IF EXISTS v_employee_cols                  ;
DROP VIEW IF EXISTS v_employee_role                  ;
SET FOREIGN_KEY_CHECKS = 1;